name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip3 install pygments
      
    - name: Install Swift
      uses: fwal/setup-swift@v1
    - run: swift --version
        
    - name: Build Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        swift build -c release
        sudo install .build/release/publish-cli /usr/local/bin/publish

    - name: Generate Site
      run: publish generate

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Output